# Generated by Django 5.2.5 on 2025-08-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='recurrencia',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', max_length=20),
        ),
    ]
